### Endpoint de teste
GET http://localhost:3003/ping

### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Guilherme",
    "email": "guilherme@gmail.com",
    "password": "gui666"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### Get shows
GET http://localhost:3003/shows

### 3) Create show
POST http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDgyODU5OCwiZXhwIjoxNjY0OTE0OTk4fQ._vmB4NLMHTZ_f1x-GcevLythCk2r_iEil60C5QdWki8
Content-Type: application/json

{
    "band": "Ozzy Osborne",
    "startsAt": "2022/12/08"
}

### Buy ticket
POST http://localhost:3003/shows/203/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg2MTc4MCwiZXhwIjoxNjYwOTQ4MTgwfQ.aewe7BjvgHu2TU90QKcTqAAGBpmz0KrYL47ChudMLPY

